# Generated by Django 2.2.5 on 2021-04-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20210209_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
